php-version = "8.2.0"

[source]
workspace = "."
paths = ["src/", "tests/", "updateRanges.php"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["phpunit"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
assert-description = { enabled = false }
assertion-style = { style = "self" }
no-boolean-flag-parameter = { enabled = false }
too-many-methods = { enabled = false }
no-else-clause = { enabled = false }
braced-string-interpolation = { enabled = false }
prefer-early-continue = { enabled = false }
cyclomatic-complexity = { enabled = false }
kan-defect = { enabled = false }

[analyzer]
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
allow-possibly-undefined-array-keys = false
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = true
check-missing-type-hints = true
register-super-globals = true
excludes=["tests/", "updateRanges.php"]
